{% set name = "mkdocs-table-reader-plugin" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 445142b334f18b61aa2e4548eb2f5177d5b4563c4d663c853ce82828b7a37ec2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mkdocs >=1.0
    - pandas >=1.1
    - tabulate >=0.8.7
    - PyYAML >=5.4.1

test:
  imports:
    - mkdocs_table_reader_plugin
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://timvink.github.io/mkdocs-table-reader-plugin/#documentation
  summary: MkDocs plugin to directly insert tables from files into markdown.
  description: MkDocs plugin to directly insert tables from files into markdown.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://timvink.github.io/mkdocs-table-reader-plugin/#documentation
  dev_url: https://github.com/timvink/mkdocs-table-reader-plugin

extra:
  recipe-maintainers:
    - cpcloud
